### ISSUE TITLE
运行示例代码然后打开previewer报错

### ISSUE THREAD

**Issue by nanyanghuayuan** [Yuan-Mr/mcCharts#14]
[Compile Result] [webpack-cli] TypeError: Cannot read properties of undefined (reading 'replace')
[Compile Result]     at processNodeModulesFile (C:\huawei\sdk\openharmony\9\ets\build-tools\ets-loader\lib\gen_abc_plugin.js:1:8295)
[Compile Result]     at processEtsModule (C:\huawei\sdk\openharmony\9\ets\build-tools\ets-loader\lib\gen_abc_plugin.js:1:9306)
[Compile Result]     at C:\huawei\sdk\openharmony\9\ets\build-tools\ets-loader\lib\gen_abc_plugin.js:1:13650
[Compile Result]     at Set.forEach (<anonymous>)
[Compile Result]     at handleFullModuleFiles (C:\huawei\sdk\openharmony\9\ets\build-tools\ets-loader\lib\gen_abc_plugin.js:1:13052)
[Compile Result]     at GenAbcPlugin.handleFinishModules (C:\huawei\sdk\openharmony\9\ets\build-tools\ets-loader\lib\gen_abc_plugin.js:2:3272)
[Compile Result]     at Hook.eval [as callAsync] (eval at create (C:\huawei\sdk\openharmony\9\ets\build-tools\ets-loader\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:40:1)
[Compile Result]     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\huawei\sdk\openharmony\9\ets\build-tools\ets-loader\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
[Compile Result]     at Compilation.finish (C:\huawei\sdk\openharmony\9\ets\build-tools\ets-loader\node_modules\webpack\lib\Compilation.js:2714:28)
[Compile Result]     at C:\huawei\sdk\openharmony\9\ets\build-tools\ets-loader\node_modules\webpack\lib\Compiler.js:1182:19
[Compile Result] Compile error occurred. Fix it based on the above message.

**Comment by Yuan-Mr** [comment]
代码发出来看看
