### ISSUE TITLE
创建@state defOptions: Options = new Options({})时会报错

### ISSUE THREAD

**Issue by shuchangxiao** [Yuan-Mr/mcCharts#28]

**Comment by shuchangxiao** [comment]
[Compile Result] [webpack-cli] TypeError: Cannot read properties of undefined (reading 'replace')
[Compile Result]     at processNodeModulesFile (E:\Huawei\sdk\openharmony\9\ets\build-tools\ets-loader\lib\gen_abc_plugin.js:1:8295)
[Compile Result]     at processEtsModule (E:\Huawei\sdk\openharmony\9\ets\build-tools\ets-loader\lib\gen_abc_plugin.js:1:9306)
[Compile Result]     at E:\Huawei\sdk\openharmony\9\ets\build-tools\ets-loader\lib\gen_abc_plugin.js:1:13650
[Compile Result]     at Set.forEach (<anonymous>)
[Compile Result]     at handleFullModuleFiles (E:\Huawei\sdk\openharmony\9\ets\build-tools\ets-loader\lib\gen_abc_plugin.js:1:13052)
[Compile Result]     at GenAbcPlugin.handleFinishModules (E:\Huawei\sdk\openharmony\9\ets\build-tools\ets-loader\lib\gen_abc_plugin.js:2:3272)
[Compile Result]     at Hook.eval [as callAsync] (eval at create (E:\Huawei\sdk\openharmony\9\ets\build-tools\ets-loader\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:40:1)
[Compile Result]     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (E:\Huawei\sdk\openharmony\9\ets\build-tools\ets-loader\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
[Compile Result]     at Compilation.finish (E:\Huawei\sdk\openharmony\9\ets\build-tools\ets-loader\node_modules\webpack\lib\Compilation.js:2714:28)
[Compile Result]     at E:\Huawei\sdk\openharmony\9\ets\build-tools\ets-loader\node_modules\webpack\lib\Compiler.js:1182:19
[Compile Result] Compile error occurred. Fix it based on the above message.

**Comment by Yuan-Mr** [comment]
编辑器版本问题，请使用最新的编辑器或者重新更新编辑器

**Comment by Yuan-Mr** [comment]
可以加入我们群哈，群里可以发开发模版给你

**Comment by Yuan-Mr** [comment]
已经更新2.0，你可以更新到2.0试试看还会不会哈
